use noloong_app::{
    AppInteractionEndpoint, AppInteractionStatus, AppLaunchOptions, AppRuntimeControlEndpoint,
    AppRuntimeRestartResult,
    interaction::{
        AppApprovalResolveRequest, AppDisplayEvent, AppDisplaySubscribeRequest,
        AppInteractionDisplayNotification, AppInteractionSessionDescriptor, AppMessage,
        AppPromptInput, AppPromptRequest, AppSessionCreateRequest, AppSessionListRequest,
        AppSessionMetadataUpdateRequest, AppSessionRequest, AppSubscriptionResult,
        InteractionInitializeRequest, InteractionInitializeResult,
    },
    profile_config::{
        AppProfileConfigCompletionRequest, AppProfileConfigCompletionSet, AppProfileConfigDocument,
        AppProfileConfigSaveRequest, AppProfileConfigValidateRequest,
        AppProfileConfigValidationResult,
    },
};
use noloong_config::HostProfileConfig;
use schemars::{Schema, schema_for};
use serde_json::Value;
use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::PathBuf,
};

#[test]
fn typescript_contracts_are_current() {
    let expected = generated_typescript_contracts();
    let path = generated_contracts_path();

    if env::var_os("NOLOONG_UPDATE_TS_CONTRACTS").is_some() {
        fs::create_dir_all(path.parent().expect("generated contracts directory"))
            .expect("create generated contracts directory");
        fs::write(&path, &expected).expect("write generated TypeScript contracts");
    }

    let actual = fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "{} is missing or unreadable: {error}. Run NOLOONG_UPDATE_TS_CONTRACTS=1 cargo test -p noloong-app typescript_contracts_are_current",
            path.display()
        );
    });

    assert_eq!(
        actual,
        expected,
        "{} is stale. Run NOLOONG_UPDATE_TS_CONTRACTS=1 cargo test -p noloong-app typescript_contracts_are_current",
        path.display()
    );
}

fn generated_typescript_contracts() -> String {
    let contracts = contracts();
    let mut output = String::from(
        "/* eslint-disable */\n\
         // This file is generated by crates/noloong-app/tests/typescript_contracts.rs.\n\
         // Do not edit it by hand.\n\n",
    );

    for contract in &contracts {
        output.push_str(&contract.render_schema_const());
    }

    output.push_str(&render_type_declarations(&contracts));
    output
}

fn render_type_declarations(contracts: &[TypescriptContract]) -> String {
    let mut definitions = BTreeMap::new();
    for contract in contracts {
        collect_definitions(&contract.schema_value(), &mut definitions);
    }

    let root_names = contracts
        .iter()
        .map(|contract| contract.type_name)
        .collect::<BTreeSet<_>>();
    let mut output = String::from("export type JsonUnknown = unknown;\n\n");

    for (name, schema) in definitions {
        let type_name = sanitize_type_name(&name);
        if root_names.contains(type_name.as_str()) {
            continue;
        }
        output.push_str(&render_type_alias(&type_name, &schema));
    }

    for contract in contracts {
        output.push_str(&render_type_alias(
            contract.type_name,
            &contract.schema_value(),
        ));
    }

    output
}

fn contracts() -> Vec<TypescriptContract> {
    vec![
        TypescriptContract::new(
            "appLaunchOptionsSchema",
            "AppLaunchOptions",
            schema_for!(AppLaunchOptions),
        ),
        TypescriptContract::new(
            "hostProfileConfigSchema",
            "HostProfileConfig",
            schema_for!(HostProfileConfig),
        ),
        TypescriptContract::new(
            "appInteractionEndpointSchema",
            "AppInteractionEndpoint",
            schema_for!(AppInteractionEndpoint),
        ),
        TypescriptContract::new(
            "appInteractionStatusSchema",
            "AppInteractionStatus",
            schema_for!(AppInteractionStatus),
        ),
        TypescriptContract::new(
            "appRuntimeControlEndpointSchema",
            "AppRuntimeControlEndpoint",
            schema_for!(AppRuntimeControlEndpoint),
        ),
        TypescriptContract::new(
            "appRuntimeRestartResultSchema",
            "AppRuntimeRestartResult",
            schema_for!(AppRuntimeRestartResult),
        ),
        TypescriptContract::new(
            "interactionInitializeRequestSchema",
            "InteractionInitializeRequest",
            schema_for!(InteractionInitializeRequest),
        ),
        TypescriptContract::new(
            "interactionInitializeResultSchema",
            "InteractionInitializeResult",
            schema_for!(InteractionInitializeResult),
        ),
        TypescriptContract::new(
            "appSessionCreateRequestSchema",
            "AppSessionCreateRequest",
            schema_for!(AppSessionCreateRequest),
        ),
        TypescriptContract::new(
            "appSessionListRequestSchema",
            "AppSessionListRequest",
            schema_for!(AppSessionListRequest),
        ),
        TypescriptContract::new(
            "appSessionRequestSchema",
            "AppSessionRequest",
            schema_for!(AppSessionRequest),
        ),
        TypescriptContract::new(
            "appSessionMetadataUpdateRequestSchema",
            "AppSessionMetadataUpdateRequest",
            schema_for!(AppSessionMetadataUpdateRequest),
        ),
        TypescriptContract::new(
            "appPromptRequestSchema",
            "AppPromptRequest",
            schema_for!(AppPromptRequest),
        ),
        TypescriptContract::new(
            "appPromptInputSchema",
            "AppPromptInput",
            schema_for!(AppPromptInput),
        ),
        TypescriptContract::new("appMessageSchema", "AppMessage", schema_for!(AppMessage)),
        TypescriptContract::new(
            "appApprovalResolveRequestSchema",
            "AppApprovalResolveRequest",
            schema_for!(AppApprovalResolveRequest),
        ),
        TypescriptContract::new(
            "appDisplaySubscribeRequestSchema",
            "AppDisplaySubscribeRequest",
            schema_for!(AppDisplaySubscribeRequest),
        ),
        TypescriptContract::new(
            "appSubscriptionResultSchema",
            "AppSubscriptionResult",
            schema_for!(AppSubscriptionResult),
        ),
        TypescriptContract::new(
            "appInteractionSessionDescriptorSchema",
            "AppInteractionSessionDescriptor",
            schema_for!(AppInteractionSessionDescriptor),
        ),
        TypescriptContract::new(
            "appDisplayEventSchema",
            "AppDisplayEvent",
            schema_for!(AppDisplayEvent),
        ),
        TypescriptContract::new(
            "appInteractionDisplayNotificationSchema",
            "AppInteractionDisplayNotification",
            schema_for!(AppInteractionDisplayNotification),
        ),
        TypescriptContract::new(
            "appProfileConfigDocumentSchema",
            "AppProfileConfigDocument",
            schema_for!(AppProfileConfigDocument),
        ),
        TypescriptContract::new(
            "appProfileConfigValidateRequestSchema",
            "AppProfileConfigValidateRequest",
            schema_for!(AppProfileConfigValidateRequest),
        ),
        TypescriptContract::new(
            "appProfileConfigSaveRequestSchema",
            "AppProfileConfigSaveRequest",
            schema_for!(AppProfileConfigSaveRequest),
        ),
        TypescriptContract::new(
            "appProfileConfigValidationResultSchema",
            "AppProfileConfigValidationResult",
            schema_for!(AppProfileConfigValidationResult),
        ),
        TypescriptContract::new(
            "appProfileConfigCompletionRequestSchema",
            "AppProfileConfigCompletionRequest",
            schema_for!(AppProfileConfigCompletionRequest),
        ),
        TypescriptContract::new(
            "appProfileConfigCompletionSetSchema",
            "AppProfileConfigCompletionSet",
            schema_for!(AppProfileConfigCompletionSet),
        ),
    ]
}

struct TypescriptContract {
    schema_const: &'static str,
    type_name: &'static str,
    schema: Schema,
}

impl TypescriptContract {
    fn new(schema_const: &'static str, type_name: &'static str, schema: Schema) -> Self {
        Self {
            schema_const,
            type_name,
            schema,
        }
    }

    fn schema_value(&self) -> Value {
        serde_json::to_value(&self.schema).expect("schema should serialize to JSON")
    }

    fn render_schema_const(&self) -> String {
        let schema = serde_json::to_string_pretty(&self.schema_value())
            .expect("schema should serialize to JSON");
        format!(
            "export const {schema_const} = {schema} as const;\n\
             \n",
            schema_const = self.schema_const,
        )
    }
}

fn render_type_alias(type_name: &str, schema: &Value) -> String {
    let definition = type_from_schema(schema);
    format!("export type {type_name} = {definition};\n\n")
}

fn collect_definitions(schema: &Value, definitions: &mut BTreeMap<String, Value>) {
    let Some(object) = schema.as_object() else {
        return;
    };

    if let Some(defs) = object.get("$defs").and_then(Value::as_object) {
        for (name, definition) in defs {
            if let Some(existing) = definitions.insert(name.clone(), definition.clone()) {
                assert_eq!(
                    existing, *definition,
                    "conflicting schema definition: {name}"
                );
            }
            collect_definitions(definition, definitions);
        }
    }

    for value in object.values() {
        match value {
            Value::Array(values) => {
                for item in values {
                    collect_definitions(item, definitions);
                }
            }
            Value::Object(_) => collect_definitions(value, definitions),
            _ => {}
        }
    }
}

fn type_from_schema(schema: &Value) -> String {
    match schema {
        Value::Bool(true) => "JsonUnknown".into(),
        Value::Bool(false) => "never".into(),
        Value::Object(object) => type_from_schema_object(object),
        _ => "JsonUnknown".into(),
    }
}

fn type_from_schema_object(object: &serde_json::Map<String, Value>) -> String {
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        return type_from_reference(reference);
    }

    if let Some(value) = object.get("const") {
        return literal_type(value);
    }

    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        return union_type(values.iter().map(literal_type));
    }

    if let Some(values) = object.get("oneOf").and_then(Value::as_array) {
        return union_type(values.iter().map(type_from_schema));
    }

    if let Some(values) = object.get("anyOf").and_then(Value::as_array) {
        return union_type(values.iter().map(type_from_schema));
    }

    if let Some(values) = object.get("allOf").and_then(Value::as_array) {
        let parts = values
            .iter()
            .map(type_from_schema)
            .filter(|value| value != "JsonUnknown")
            .collect::<Vec<_>>();
        return if parts.is_empty() {
            "JsonUnknown".into()
        } else {
            parts.join(" & ")
        };
    }

    match object.get("type") {
        Some(Value::String(kind)) => type_from_json_kind(kind, object),
        Some(Value::Array(kinds)) => union_type(
            kinds
                .iter()
                .filter_map(|kind| kind.as_str().map(|kind| type_from_json_kind(kind, object))),
        ),
        _ if object.contains_key("properties") => object_type(object),
        _ if object.contains_key("additionalProperties") => object_type(object),
        _ => "JsonUnknown".into(),
    }
}

fn type_from_json_kind(kind: &str, object: &serde_json::Map<String, Value>) -> String {
    match kind {
        "string" => "string".into(),
        "number" | "integer" => "number".into(),
        "boolean" => "boolean".into(),
        "null" => "null".into(),
        "array" => array_type(object),
        "object" => object_type(object),
        _ => "JsonUnknown".into(),
    }
}

fn array_type(object: &serde_json::Map<String, Value>) -> String {
    let item_type = object
        .get("items")
        .map(type_from_schema)
        .unwrap_or_else(|| "JsonUnknown".into());
    format!("Array<{item_type}>")
}

fn object_type(object: &serde_json::Map<String, Value>) -> String {
    let properties = object
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();

    if properties.is_empty() {
        return match object.get("additionalProperties") {
            Some(Value::Object(_)) | Some(Value::Bool(_)) => {
                let item_type = object
                    .get("additionalProperties")
                    .map(type_from_schema)
                    .unwrap_or_else(|| "JsonUnknown".into());
                format!("Record<string, {item_type}>")
            }
            _ => "Record<string, JsonUnknown>".into(),
        };
    }

    let required = object
        .get("required")
        .and_then(Value::as_array)
        .map(|values| {
            values
                .iter()
                .filter_map(Value::as_str)
                .collect::<BTreeSet<_>>()
        })
        .unwrap_or_default();

    let mut lines = Vec::with_capacity(properties.len());
    for (name, schema) in properties {
        let optional = if required.contains(name.as_str()) {
            ""
        } else {
            "?"
        };
        let field_type = indent_continuation(&type_from_schema(&schema), 2);
        lines.push(format!(
            "  {property}{optional}: {field_type};",
            property = property_name(&name),
        ));
    }

    format!("{{\n{}\n}}", lines.join("\n"))
}

fn type_from_reference(reference: &str) -> String {
    reference
        .strip_prefix("#/$defs/")
        .map(sanitize_type_name)
        .unwrap_or_else(|| "JsonUnknown".into())
}

fn sanitize_type_name(name: &str) -> String {
    let mut output = String::with_capacity(name.len());
    for character in name.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            output.push(character);
        } else {
            output.push('_');
        }
    }

    if output
        .chars()
        .next()
        .is_none_or(|character| !character.is_ascii_alphabetic() && character != '_')
    {
        output.insert(0, '_');
    }

    output
}

fn property_name(name: &str) -> String {
    serde_json::to_string(name).expect("property name should serialize")
}

fn literal_type(value: &Value) -> String {
    match value {
        Value::Null => "null".into(),
        Value::Bool(value) => value.to_string(),
        Value::Number(value) => value.to_string(),
        Value::String(value) => serde_json::to_string(value).expect("string literal serializes"),
        _ => "JsonUnknown".into(),
    }
}

fn union_type(values: impl IntoIterator<Item = String>) -> String {
    let mut values = values.into_iter().collect::<Vec<_>>();
    values.sort();
    values.dedup();
    match values.len() {
        0 => "never".into(),
        1 => values.pop().expect("one value"),
        _ => values.join(" | "),
    }
}

fn indent_continuation(value: &str, spaces: usize) -> String {
    let indent = " ".repeat(spaces);
    value.replace('\n', &format!("\n{indent}"))
}

fn generated_contracts_path() -> PathBuf {
    repository_root().join("apps/desktop/src/generated/contracts.ts")
}

fn repository_root() -> PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("repository root")
        .to_path_buf()
}
